[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,
data_dir = /var/lib/odoo
log_handler = [':INFO']
log_level = info
admin_passwd = Fixon.1007
proxy_mode = True
http_port = 8069
workers = 2
max_cron_threads = 1
limit_time_cpu = 60
limit_time_real = 120
dbfilter = .*